name: 'adventure_work'
version: '1.0.0'
config-version: 2

profile: 'adventure_work'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  adventure_work:
    +catalog: fea_academy

    staging:
      +schema: stg
      +materialized: view

    intermediate:
      +schema: int
      +materialized: view   

    marts:
      +schema: mart
      +materialized: table